sudo: true
language: haskell

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.6.5
  - ghc: 8.4.4
  - ghc: 8.2.2
  - ghc: 8.0.2
  - ghc: 7.10.3
  - ghc: 7.8.4

install:
  - cabal new-update
  - cabal new-build

script:
  - echo 'No tests'

notifications:
  email: false
