language: haskell

cabal: "2.4"

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.cabal"

ghc:
  - 8.10.1
  - 8.8.3
  - 8.6.5
  - 8.4.4
  - 8.2.2
  - 8.0.2
  - 7.10.3
  - 7.8.4
  - 7.6.3

install:
  - cabal new-update

script:
  - cabal new-build

notifications:
  email: false
